### ISSUE TITLE
kubicorn apply messes up existing kube config

### ISSUE THREAD

**Issue by deitch** [kubicorn/kubicorn#496]
If I run `kubicorn apply`, it does the right thing by adding the cluster/user/context to my `~/.kube/.config`. 

But it does it by adding a brand-new entire set of yml to the end of the file. This means that I lose all of my existing unless I manually delete it. 

I don't know if it always does it, or if it has a hard time with certain structured kube config files.

**Comment by xmudrii** [comment]
@deitch Thank you very much for reporting the issue. There're some reported problems with deleting kubeconfig already (#384). I'll look into it once I get some free time.

**Comment by stealthybox** [comment]
Related to solving this issue: #110

**Comment by davecaplinger** [comment]
Writing the config to a different local file path (which is what I think #500 allows?) seems like the wrong approach to fix this issue (in my opinion, of course).  For example, I have multiple cluster configs in `~/.kube/config` so I can easily switch with `kubectx` and as @deitch indicated, the new cluster info that kubicorn added got written to the right file; just not the right place in that file.  Further, the default context, cluster, and user names that kubicorn wrote conflicted with existing entries.

Since the config file has a only a flat list of users that are distinguished only by name, the names themselves are not cluster-specific, and if two contexts refer to the same user name, there's no way to determine which name is the correct one for that context.  So it would be bad to overwrite or duplicate the name used by some other cluster's context in the config file.

Since the name itself seems to be just a local label (the `server`, `key-data`, and `certificate-data` are the important bits), then the user, cluster, and context names that kubicorn uses could just replace the word "kubernetes" with "kubicorn-" plus the cluster name, such as `myfirstk8s: kubicorn-myfirstk8s-admin@kubicorn-myfirstk8s`.  That would also help ensure that if you're using kubicorn simultaneously for multiple clusters, changes to one profile don't overwrite the other as long as their cluster names are unique.

**Comment by stealthybox** [comment]
Thanks @davecaplinger,
I think we can all agree on your suggested approach.

We recently vendored kubernetes/client-go in anticipation of this (as well as other efforts)
The current implementation literally copies kubeadm's kubeconfig, so we'll need to write one that is struct aware.

There are more linked issues here as well: https://github.com/kris-nova/kubicorn/issues/56

**Comment by ashish-amarnath** [comment]
The problem here is that the `GetConfig` function reads the kubeconfig from remote and writes into a local file kubeconfig file without parsing the bytes it read as kubeconfig. For the same reason, it will not be able to store configs for multiple clusters.

I can see two potential fixes here:
1.  Create a kubeconfig file per cluster and 
2. Parse the bytes read from the remote kubeconfig and append as kubeconfig.

IMO, it would be beneficial to do both, create a kubeconfig per cluster and also maintain a kubeconfig with all the clusters. WDYT?
Happy to work on the fix for this and you can assign this to me.

**Comment by xmudrii** [comment]
@ashish-amarnath I can't assign you to the issue for some reason (possibly because you're the first-time contributor, so GitHub isn't allowing it), but I have applied WorkInProgress label to the issue.

This sounds great. I've seen the PR and it is shaping nicely.

For now, parsing the bytes and merging it with the existing kubeconfig is a great solution. We could possibly add some flag if user want to specify non-default kubeconfig, existing or non-existing.

Thank you for contributing! If you have any questions, let me know :)

**Comment by xmudrii** [comment]
Fixed by #658

**Comment by ashish-amarnath** [comment]
@deitch  This is now fixed. Mind giving it a try and letting us know if it works for you?

**Comment by deitch** [comment]
I can confirm that it is fixed. It keeps me existing config and adds the new one.

FYI, when I delete a cluster with `kubicorn delete`, it does _not_ remove it from `kubeconfig`, which it probably should. I assume this already has been reported though?

**Comment by xmudrii** [comment]
> FYI, when I delete a cluster with kubicorn delete, it does not remove it from kubeconfig, which it probably should. I assume this already has been reported though?

@deitch 👍 could be an interesting feature.

the only problem we could have is what if user renames the cluster in kubeconfig, but I guess in that case we can just skip it.

**Comment by stealthybox** [comment]
I haven't run across tooling that automatically deletes kubeconfig entries when deleting infrastructure. This seems dangerous unless kubicorn includes unique id's in the kubeconfig objects.

Would be good if there are examples of other tools doing this.

**Comment by ashish-amarnath** [comment]
I haven't seen tools do this.. but the setup I have seen, creating clusters using terraform driven by `make`, we purge the kubeconfig on cluster delete. I think it would be ideal behavior, esp, if you are constantly trying to create and destroy clusters. I started a PR to implement the purge functionality but isn't hooked up to the cluster delete scenario. This is what I have so far... https://github.com/kubicorn/kubicorn/pull/668
