### ISSUE TITLE
Keypair's not removed when deleting cluster

### ISSUE THREAD

**Issue by ulrichSchreiner** [kubicorn/kubicorn#597]
hi,

i created a cluster named "testk8s" on AWS with my ssh-key "id_rsa". everything fine. then i did a `kubicorn delete testk8s` and the servers and clusters have gone.

after that i created a new cluster with the same name, but now i changed the `publicKeyPath` in the state file. when apply'ing everything is created but now kubicorn cannot fetch the configuration, because (at least at aws) there is a keypair named "testk8s" which was not removed when i deleted the old cluster. so the instances are created with my old key (from my first cluster), but kubicorn tries to connect with my new key.

solution: delete all ressources manually from AWS and also delete the Keypair. when creating the new cluster the keypar is recreated with the new keys.

**Comment by xmudrii** [comment]
‎‎As far as I know, SSH Keys are intentionally not removed, because they can be used by other resources on your account. There should be an environment variable to force key deletion, such as `KUBICORN_FORCE_DELETE_KEY`.

However the error shouldn't happen, and I can take a look to see what's going on. Currently there're some bugs with `getconfig` but I hope we'll be able to solve them as soon as possible.

**Comment by kris-nova** [comment]
Agree with @ulrichSchreiner - anybody care to PR this?
